name: transcriber
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.4
  - ld_impl_linux-64=2.44
  - libexpat=2.7.4
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.19
  - packaging=25.0
  - pip=26.0.1
  - pthread-stubs=0.3
  - python=3.11.14
  - readline=8.3
  - setuptools=80.10.2
  - sqlite=3.51.1
  - tk=8.6.15
  - tzdata=2025c
  - wheel=0.46.3
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - annotated-types==0.7.0
      - anthropic==0.79.0
      - anyio==4.12.1
      - assemblyai==0.51.0
      - certifi==2026.1.4
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - cryptography==46.0.5
      - defusedxml==0.7.1
      - distro==1.9.0
      - docstring-parser==0.17.0
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.29.0
      - google-api-python-client==2.189.0
      - google-auth==2.49.0.dev0
      - google-auth-httplib2==0.3.0
      - google-generativeai==0.8.6
      - googleapis-common-protos==1.72.0
      - grpcio==1.78.0
      - grpcio-status==1.71.2
      - h11==0.16.0
      - httpcore==1.0.9
      - httplib2==0.31.2
      - httpx==0.28.1
      - idna==3.11
      - jiter==0.13.0
      - openai==2.20.0
      - proto-plus==1.27.1
      - protobuf==5.29.6
      - pyasn1==0.6.2
      - pyasn1-modules==0.4.2
      - pycparser==3.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydub==0.25.1
      - pyparsing==3.3.2
      - requests==2.32.5
      - sniffio==1.3.1
      - tqdm==4.67.3
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - uritemplate==4.2.0
      - urllib3==2.6.3
      - websockets==16.0
      - youtube-transcript-api==1.2.4
      - yt-dlp==2026.2.4
prefix: /home/davide/miniconda3/envs/transcriber
